name:                snmp-web-service
version:             0.1.0.0
github:              "p-alik/snmp-web-service"
license:             BSD3
author:              "Alexei Pastuchov"
maintainer:          "info@maximka.de"
copyright:           "Copyright (c) 2019 Alexei Pastuchov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/p-alik/snmp-web-service#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- attoparsec
- bytestring
- ip
- language-asn
- mtl
- optparse-applicative
- servant
- servant-server
- snmp
- text
- transformers
- vector
- warp

library:
  source-dirs: src

ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints

executables:
  snmp-web-service-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snmp-web-service

tests:
  snmp-web-service-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snmp-web-service
